### PR TITLE
marekhorst #37 exporter module serializing actions to json

### PR DESCRIPTION
**Pull request by marekhorst**
This feature is related to new CDH5->CDH4 compatible exporter module writing actionsets as sequence files with JSON records instead of exporting them directly as protobufs to HBase.

More details can be found in #37 issue.

Please review.

### CODE REVIEW

**Comment by mkobos** [comment]
I think that we should stick to the convention that the pull request should be named the same as the commit corresponding to this request and the commit itself should have a form of "Closes #$ISSUE_NUMBER".

**Comment by mkobos** [comment]
I'm done with the review, please take a look.

**Comment by mkobos** [comment]
One more thing: we should have some tests covering this functionality.

**Comment by marekhorst** [comment]
Regarding the tests: I am all for it. This will take some time, so I will suggest creating separate issue for this task.

**Comment by marekhorst** [comment]
I've just pushed bunch of fixes requested in comments.

**Comment by mkobos** [comment]
> Regarding the tests: I am all for it. This will take some time, so I will suggest creating separate issue for this task.

Agree. Taking into consideration that we've got a lot of close deadlines upon us, this is the only option. I think that in the future, the tests should be a standard part of pull requests.

**Comment by mkobos** [comment]
I'm done with answering, please take a look.

**Comment by marekhorst** [comment]
Sure. I've created #73 ticket to track test related task.

**Comment by marekhorst** [comment]
I've just committed lighter version of `run()` method.

**Comment by mkobos** [comment]
Still, at ~50 lines not exactly a short method, but more readable. 

Looks good to me.

**Pull request closed without merging**
