### PR TITLE
marekhorst #1527 infospace dump import

### PR DESCRIPTION
**Pull request by marekhorst**
Introducing functionality described in [#1527](https://issue.openaire.research-infrastructures.eu/issues/1527): importing hbase dump stored as sequence file into hbase.

### CODE REVIEW

**Comment by mkobos** [comment]
I'm done with the review. Please check the comments.

I think that before sending these commits as a pull request you should have squashed the changes into a single commit. This would save me from inspecting the code that became deprecated and was eventually removed in subsequent commits as well as the one that was introduced only temporarily.

Apart from that, looks good!

**Comment by marekhorst** [comment]
I've just pushed 2 commits:
* applying changes suggested in your review
* enabling hbase import in `primary` workflow by supporting newly introduced `import_hbase_dump_location` input parameter

Can you take a look at those changes?

**Comment by mkobos** [comment]
I'm done, please take a look at the comments.

**Comment by marekhorst** [comment]
I've updated branch with master and added two fixes. Let me know if I can merge it.

**Comment by mkobos** [comment]
Looks fine, please take a look at comment https://github.com/openaire/iis/pull/14#commitcomment-13425160 though.

**Comment by mkobos** [comment]
Looks good to me.

**Pull request closed without merging**
