### PR TITLE
Tara matching upgrade to V2

### PR DESCRIPTION
**Pull request by sosguns2002**

### CODE REVIEW

**Comment by sosguns2002** [comment]
I added the missing maddis function

**Comment by sosguns2002** [comment]
Here you are, my fault again...

**Comment by sosguns2002** [comment]
Marek can you see the 4th commit? I'm not sure I made correctly the Pull rquest

**Comment by marekhorst** [comment]
> Marek can you see the 4th commit? I'm not sure I made correctly the Pull rquest

You mean this one: 5ff8639385210f4de5f841779cd6b00ea6e6d60e? Yes I can see it.

**Comment by sosguns2002** [comment]
Yes this one! Nice. I'm not familiar with Pull Request page :)

**Comment by marekhorst** [comment]
I guess we can close this one as the TARA case is going to be covered by dedicated scripts?

**Pull request closed without merging**
