### PR TITLE
Closes #7: fix all build errors

### LINKED ISSUE #7: fix all build errors occurring after migrating IIS source code from svn to git
We should fix all build errors occurring when building packages and performing both unit and integration tests.

### PR DESCRIPTION
**Pull request by marekhorst**
Refactoring can be narrowed down to the following areas:
* adding `build` and `bin` subdirectories to `.gitignore` to prevent adding compiled resources to GIT
* adding `dnet4-bootstrap-snapshot` and `dnet4-bootstrap-release` openaire repositories to main `pom.xml` file. It provides parents required by other DNet modules.
* adding `dnet4-bootstrap-snapshot` and `dnet4-bootstrap-release` openaire plugin repositories to `iis-workflows/pom.xml` file. It contains primer plugin required by workflow modules. We can discuss whether we should keep deploying this plugin to dnet bootstrap repository or move it somewhere else
* moving `iis-core-examples` to `iis-workflows/iis-workflows-core-examples` because it contains workflows thus requires priming
* fixing various unit and integration tests mostly by updating resources locations in `workflow.xml` files and java classes, UDFs package names in PIG scripts etc
* 3 integration tests from `iis-workflows-referenceextraction` module related to project referenceextraction are stil failing due to reopened [#1304](https://issue.openaire.research-infrastructures.eu/issues/1304#note-31) redmine issue

### CODE REVIEW

**Comment by marekhorst** [comment]
One more thing: there is one huge refactoring to be done I didn't feel like doing right now: renaming all packages and paths in `iis-workflows/iis-workflows-core-examples` (by adding `workflows` part) after moving those resources from `iis-core-examples`. This looks like overkill.

**Comment by marekhorst** [comment]
@mkobos can you check whether all `README.markdown` files you have modified are there? I looked briefly and didn't find anything wrong. I had to merge manually your files from `iis-workflows-core-examples` because git was unable to merge your #3 changes with moved directory to `iis-workflows` and renamed to `iis-workflows-core-examples`.

**Comment by mkobos** [comment]
The commit history is quite confusing: there are 2 commits with the same descriptions: ac8f58ae33117254faf081cc118bc37691a5bc04 and d5d01d00c06896c3b18534a277143e37b4ca9d39 and the same (or maybe similar) content. Apart from that, when I fetched your branch and examined its history with `gitk` I got this:

screenshot from 2015-09-16 23 18 53

i.e. the history is not linear. Can you squash all of your commits into a single one? I think that this will solve both problems. This will also make my job of doing the review easier since I'll have to look through one commit only and not couple inter-related ones.

**Comment by mkobos** [comment]
I'm done with doing the review. Please check the comments.

**Comment by mkobos** [comment]
> One more thing: there is one huge refactoring to be done I didn't feel like doing right now: renaming all packages and paths in iis-workflows/iis-workflows-core-examples (by adding workflows part) after moving those resources from iis-core-examples. This looks like overkill.

Is that really that time-consuming?

**Comment by mkobos** [comment]
Starting another thread :)

> @mkobos can you check whether all README.markdown files you have modified are there?

It seems fine

**Comment by marekhorst** [comment]
I've added new commits fixing the following issues:

* changing java version to `1.6` in maven compiler (required by CDH4)
* updating `.gitignore`
* properties cleanup in main `pom.xml` file
* renaming `iis-core-examples` to `iis-workflows-core-examples` in `readme.markdown` files

Can you revise it?

**Comment by mkobos** [comment]
Looks good to me

**Comment by marekhorst** [comment]
All changes from feature branch were merged with master.

**Pull request closed without merging**
