### PR TITLE
Closes #1234: Remove project concept matching phase

### LINKED ISSUE #1234: Multiple requests when retrieving content from external services
Running cached webcrawler job for issue #1136 revealed that we're retrieving content from external services multiple times. For example running the job with only a single site to read results in three requests. We should send only one request for each site to read. This looks like a Spark caching problem, that is we're not caching the responses from the services and when another Spark action is called with the same RDD we're executing the whole plan again.

We should fix this for cached webcrawler and check if the same situation is for patent metadata retriever.

### PR DESCRIPTION
**Pull request by marekhorst**
Supplementary pull request related description:

Two integration tests were run (`primary/processing` and `export/actionmanager/sequencefile`) proving the introduced changes did not break those workflows.

The original description from the commit message:

This commit removes support for matching concepts (listed in `import_project_concepts_context_ids_csv` IIS input parameter) with publications linked to projects associated with those concepts.

The reason for the removal is this code is now overlapping with the community bulk tagging functionality implemented in a different module being a part of the provisioning chain.

The result of the removal is manifested by the lack of the Oaf publication records encapsulating the concepts (defined as contexts) associated with publications in the output actionset identified with the `action_set_id_document_referencedProjects` input parameter. Relevant report metrics (`processing.referenceExtraction.concept.*`) are also removed.

It is enough to list communities and research initiatives only among the concepts listed as `import_project_concepts_context_ids_csv` input parameter from now on. The listed concepts will be streamed to community TDM (text data mining) and research initiatives TDM algorithms only. No matching against publications linked to projects will be performed anymore.

### CODE REVIEW

**Comment by marekhorst** [comment]
> Shouldn't it be closing #1439?

You're right, just pushed the updated commit (forced push).

**Review by mpol — APPROVED** [review]
LGTM

Makes sense as far as I can tell.

Looking for possibly missed things I only found `DatasetRefExtractionOutputTransformerWfTest.java` containing `testProjectToConceptWorkflow` but this looks more like an incorrectly named test.

**Comment by marekhorst** [comment]
Thanks. I just renamed this test to `testDatasetReferenceExtractionOutputTransformerWorkflow()` in order to avoid confusion.

**Comment by marekhorst** [comment]
Merged with this commit after applying last minute changes:
https://github.com/openaire/iis/commit/d919bae087d692d0446dfce44f672595ed5d8a63

**Pull request closed without merging**
