### PR TITLE
add unidentified gsrt

### PR DESCRIPTION
**Pull request by johnfouf**

### CODE REVIEW

**Comment by johnfouf** [comment]
@Marek, this contains an update that searched for GSRT projects with unidentified id (it is an urgent request to run from Natalia, we will send you an email with more details).

**Comment by marek** [comment]
> @marek, this contains an update that searched for GSRT projects with unidentified id (it is an urgent request to run from Natalia, we will send you an email with more details).

wrong @marek :D

**Comment by harry-di** [comment]
> > @marek, this contains an update that searched for GSRT projects with unidentified id (it is an urgent request to run from Natalia, we will send you an email with more details).

@marekhorst 
Apparently Yannis (@johnfouf) mistakenly tagged the above comments to the wrong Marek (our apologies!).

**Comment by marekhorst** [comment]
Regarding the progress of handling this PR, more details are available in a dedicated issue:

https://github.com/openaire/iis/issues/1230

This is a note for myself as I've spend some time finding out why this wasn't integrated yet...

**Comment by marekhorst** [comment]
Just realized, kind of by accident, the script update related to unidentified gsrt projects handling causes failure, in particular when running projects mining on FCT projects.

The link to the job which failed:
http://iis-cdh5-test-m3.ocean.icm.edu.pl:19888/jobhistory/job/job_1614993033499_7618

The reported problem is the following:
```
Type conversion error for field projectId, null for "string"
```
We have already been struggling with similar issue 3 years ago:
https://issue.openaire.research-infrastructures.eu/issues/2508#note-106
@johnfouf, please take a look at this, especially when this PR is going to be integrated with IIS master branch.

One additional note: the algorithm succeeded without any complains when running it on a subset of GSRT projects:
https://issue.openaire.research-infrastructures.eu/issues/3897#note-44

**Pull request closed without merging**
