### PR TITLE
#Closes 170: documenttext collapser fails with oomerr

### PR DESCRIPTION
**Pull request by marekhorst**
This one consists of 3 commits, each one improves stability.

### CODE REVIEW

**Comment by mkobos** [comment]
Dividing this pull request into three functional commits makes reviewing much easier!

**Comment by mkobos** [comment]
Commit messages are a nice documentation of the introduced change. So if eventually you want to squash the commits into a single one, its message in the second and later lines should contain this original documentation. On the other hand, one might consider leaving the original commits as they are (with potentially adding a prefix to the message of the intermediary commits like "Issue #170" so it's obvious which issue they are addressing).

**Comment by marekhorst** [comment]
I've just added some comments and committed reformatted workflow.xml files.

**Comment by mkobos** [comment]
Ok. There are two comments that require your answer: https://github.com/openaire/iis/pull/173#commitcomment-15613122, https://github.com/openaire/iis/pull/173#commitcomment-15688427

**Comment by mkobos** [comment]
Ok. What about comment https://github.com/openaire/iis/pull/173#commitcomment-15613122?

**Comment by mkobos** [comment]
LGTM

**Pull request closed without merging**
