### PR TITLE
Closes #28 create branch for CDH5 cluster compatibility

### LINKED ISSUE #28: Create branch for CDH5 cluster compatibility
This branch should be built based on `IIS-CDH-5.3.0` svn branch.

New patches possibly will have to be applied due to further changes in IIS code and CDH5 cluster version upgrade to `CDH-5.4.2`.

### PR DESCRIPTION
**Pull request by marekhorst**
Please review set of changes between master and cdh5 branch.

More details on #28 issue page.

### CODE REVIEW

**Comment by mkobos** [comment]
One of the changes in this branch is removing the `iis-3rdparty-pig-avrostorage` project from the source. However, this project is currently still in the master branch. Is this because Pig in CDH5 supports Avro out-of-the-box, while CHD4 does not?

**Comment by mkobos** [comment]
I'm done with the review, please take a look.

**Comment by marekhorst** [comment]
In case you didn't get notification on commit comment here is my answer: https://github.com/openaire/iis/commit/807c4cb943b2840abaeace2137f34131113a2c42#commitcomment-13683009

**Comment by mkobos** [comment]
I'm done with my answers, please take a look.

**Comment by mkobos** [comment]
Shouldn't we just close this ticket?

**Comment by marekhorst** [comment]
I will leave it open until merging it back to master. There are also some valuable comments we didn't take into account yet.

**Comment by mkobos** [comment]
Let me get back to the topic of closing this pull request. This pull request is shown by GitHub as open in https://github.com/openaire/iis/pulls and this gives me an impression that it is pending on our TODO list, but this has been already reviewed and don't intend to merge these changes any time soon. Thus, I think that we should close this pull request and reopen it when necessary.

**Comment by marekhorst** [comment]
I guess we have covered all the requests in pull request comments except for the one related to introducing `ProjectDBBuilder` and `DatasetDBBuilder` changes from CDH5 branch back to the master branch (which will happen after the merge anyway).

Let's close it for now.

**Pull request closed without merging**
